version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_library_web
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
      PORT: 5001
      MONGO_URI: mongodb://mongo:27017/book_library
      SECRET_KEY: ${SECRET_KEY:?SECRET_KEY not set}
    depends_on:
      mongo:
        condition: service_started
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./app/static/uploads:/app/app/static/uploads:rw
    security_opt:
      - no-new-privileges:true


  mongo:
    image: mongo:7.0
    container_name: book_library_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: book_library
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


volumes:
  mongo_data: